# Generated by Django 3.2 on 2021-04-22 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=280)),
                ('google_location', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='Menuentries',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=280)),
                ('description', models.CharField(max_length=280)),
                ('price', models.FloatField()),
                ('calories', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood.restaurants')),
            ],
            options={
                'db_table': 'menuentries',
            },
        ),
        migrations.CreateModel(
            name='TrustRatings',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fastfood.menuentries')),
                ('trust', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_ratings',
                'unique_together': {('food', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FoodRatings',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fastfood.menuentries')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=280, null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_ratings',
                'unique_together': {('food', 'user')},
            },
        ),
    ]
