version: '3'

services:
    api:
        build: ./backend
        command: sh
        volumes:
          - ./backend:/app
        ports:
          - "8000:8000"
        environment:
            POSTGRES_NAME: postgres
            POSTGRES_PASSWORD: agoodpassword    # put your superuser database password this here
            POSTGRES_USER: userdb
            POSTGRES_DB: rocketdb
        depends_on:
          - database
    frontend:
        build: ./frontend
        container_name: vue_frontend
        hostname: vue_frontend
        ports:
            - 8080:8080
        volumes:
            - ./frontend/fastfood_frontend:/frontend
            - /frontend/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: "npm run serve"
        links:
            - api
    database:
        image: postgres:13
        container_name: rocket_db
        hostname: rocket_db
        expose: 
            - 5432
        environment:
            POSTGRES_NAME: postgres
            POSTGRES_PASSWORD: agoodpassword    # put your superuser database password this here
            POSTGRES_USER: userdb
            POSTGRES_DB: rocketdb
            PGDATA: /var/lib/postgresql/data/pgdata


# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
    pgdata: {}

